### ISSUE TITLE
Deployment to Heroku Failing

### ISSUE THREAD

**Issue by qarthandgi** [thisismydesign/nestjs-starter#14] opened 2021-10-14 13:40 UTC
```bash
remote: [3/4] Linking dependencies...
remote: warning " > @nestjs/graphql@7.10.3" has unmet peer dependency "apollo-server-core@^2.21.1".
remote: warning "@nestjs/graphql > @nestjs/mapped-types@0.4.0" has unmet peer dependency "class-transformer@^0.2.0 || ^0.3.0 || ^0.4.0".
remote: warning "@nestjs/graphql > @nestjs/mapped-types@0.4.0" has unmet peer dependency "class-validator@^0.11.1 || ^0.12.0 || ^0.13.0".
remote: warning " > nestjs-console@4.0.0" has incorrect peer dependency "commander@^5 || ^6".
remote: warning " > ts-loader@8.1.0" has unmet peer dependency "webpack@*".
remote: [4/4] Building fresh packages...
remote: Done in 58.39s.
remote: Removing intermediate container ab58e930838a
remote:  ---> 706fa2085519
remote: Step 5/6 : COPY . /app
remote:  ---> f9cd92c66b01
remote: Step 6/6 : RUN yarn build
remote:  ---> Running in 68a9ab514955
remote: yarn run v1.22.15
remote: $ rimraf dist
remote: $ NODE_ENV=production nest build && cd src/client && next build
remote: Browserslist: caniuse-lite is outdated. Please run:
remote: npx browserslist@latest --update-db
remote: 
remote: Why you should do it regularly:
remote: https://github.com/browserslist/browserslist#browsers-data-updating
remote: info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
remote: info  - Checking validity of types...
remote: Attention: Next.js now collects completely anonymous telemetry regarding usage.
remote: This information is used to shape Next.js' roadmap and prioritize features.
remote: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
remote: https://nextjs.org/telemetry
remote: 
remote: info  - Creating an optimized production build...
remote: Browserslist: caniuse-lite is outdated. Please run:
remote: npx browserslist@latest --update-db
remote: 
remote: Why you should do it regularly:
remote: https://github.com/browserslist/browserslist#browsers-data-updating
remote: info  - Compiled successfully
```

These are the errors I'm getting when deploying to Heroku. Is there a reason I'm getting so many "unmet peer dependency" issues?

**Comment by thisismydesign** [comment] 2021-10-14 13:58
Those are common warnings, not related to the project. Google can help. Looks like the deployment was successful in the end so I'm closing this issue.

**Closed as completed by thisismydesign** 2021-10-14 13:59 UTC

**Comment by thisismydesign** [comment] 2021-10-14 15:14
Interesting find, I noticed that the release logs are empty when deploying a container project but never looked into the cause because I could find the logs in the app logs - as you did as well. So you found the error as well, it's about the migration failing due to missing pg_hba.conf entry. Searching for and fixing that error should help.

**Comment by qarthandgi** [comment] 2021-10-14 22:57
@kylebaskin found the fix! This template will only respect `ssl` for the database if Heroku has a `NODE_ENV` equal to `production`. That's all that's needed.

**Comment by kylebaskin** [comment] 2021-10-14 22:59
@qarthandgi So just making sure I completely understand, adding `NODE_ENV=production` to your .env.production file fixed it? Or did you add the environment variable through the command line?

**Comment by thisismydesign** [comment] 2021-11-22 01:16
@qarthandgi I added an [app.json](https://github.com/thisismydesign/nestjs-starter/blob/2f92842c8d3eb1e230fae1041ef95b499493151a/app.json) and 'deploy to heroku' button to the readme to simplify deployment. It should work out of the box. Also added `curl` to the production docker image so release logs will be visible. Thanks again for tracking both these issues down!
